# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.

keys:
  # - &admin_alice 2504791468b153b8a3963cc97ba53d1919c5dfd4
  - &admin_tjmaxxer age1ajqgzup9l269ddfk6evc9gl9pgdf6vh9vmgl6nzz23hps2k20f9qyltuf7
  - &server_tjmaxxer age1tkr0aetu5swh76m8dzkgc8fax8z276py27k9cxs2jpuy02ucdpvquft4u0
  - &admin_nix-on-droid age1ua9smjl5xw24lm5mddhvc625xr70jxwr7n86992a4un69ju9853s4vsmk2
  - &server_vps01 age1y372l3n6l0pxyj523p58m5d6nffagzgwjvgyl3h3ful2373qgvfq9fdl7a
  - &admin_elysium  age135aeczl0ykc9cfnntre8fe6y6ukw5ucp7zwvp040zzp5v9l06ees9gr0gd
  - &admin_colgate age159adtgxccsccq60y7tu5v85hndxzmzzm6dm6d4dy47pl7u3ezg4qkn686u
  - &server_colgate age1egd0sruxmj6p4vl2dn87kf360jzjv9v8ulxf40fy3v36y3c8y5nqxzkd4m

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|crt|key)$
    key_groups:
      - age:
          - *admin_tjmaxxer
          - *server_tjmaxxer
          - *admin_nix-on-droid
          - *server_vps01
          - *admin_elysium
          - *admin_colgate
          - *server_colgate
      # - pgp:
      #     - *admin_alice
