# SPDX-FileCopyrightText: 2026 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[bizhub-225i]
src.manual = "2.0.1"
fetch.url = 'https://public.integration.yamayuri.kiku8101.com/publicdownload/download?fileId=B2C0B6D9-C563-4377-B77B-33BBAC4A5EC8'
url.name = "bizhub-225i.zip"

[epson-202101w]
src.manual = "1.0.2"
fetch.url = "https://web.archive.org/web/20260318090110/https://download-center.epson.com/f/module/c863d6cc-2e0c-48f5-8a70-b2c3843c647a/epson-inkjet-printer-202101w-1.0.2-1.src.rpm"

[dms-plugins]
src.git = "https://github.com/AvengeMedia/dms-plugins.git"
fetch.github = "AvengeMedia/dms-plugins"

[matugen-themes]
src.git = "https://github.com/InioX/matugen-themes.git"
fetch.github = "InioX/matugen-themes"
