# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[default.extend-identifiers]
facter = "facter"
browseable = "browseable"
ede = "ede"
substituters = "substituters"

[default]
extend-ignore-words-re = [
  # words with length <= 4 chars is likely noise
  "^[a-zA-Z]{1,4}$",
]
