# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test machines"
on:
  push:
  workflow_call:
jobs:
  tests:
    name: "Build machine ${{ matrix.machine }}"
    runs-on: runner
    strategy:
      matrix:
        machine: [tjmaxxer, msi-colgate, vps01]
    steps:
      - uses: actions/checkout@v6
      - name: Build ${{ matrix.machine }}
        run: |
          nix build \
           .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel \
