# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bizhub-225i = {
    pname = "bizhub-225i";
    version = "2.0.1";
    src = fetchurl {
      url = "https://public.integration.yamayuri.kiku8101.com/publicdownload/download?fileId=B2C0B6D9-C563-4377-B77B-33BBAC4A5EC8";
      name = "bizhub-225i.zip";
      sha256 = "sha256-iF3FVSqDsjs6i4xeDMsUSb+0woCJ5/1lq7R0fe+x/HU=";
    };
  };
  epson-202101w = {
    pname = "epson-202101w";
    version = "1.0.2";
    src = fetchurl {
      url = "https://web.archive.org/web/20260318090110/https://download-center.epson.com/f/module/c863d6cc-2e0c-48f5-8a70-b2c3843c647a/epson-inkjet-printer-202101w-1.0.2-1.src.rpm";
      sha256 = "sha256-n0Ff2wfhPruYhzAH0GrhpYpkddiQ3rkYukvZyRgrn54=";
    };
  };
  home-manager-lib = {
    pname = "home-manager-lib";
    version = "d166a078541982a76f14d3e06e9665fa5c9ed85e";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "home-manager";
      rev = "d166a078541982a76f14d3e06e9665fa5c9ed85e";
      fetchSubmodules = false;
      sha256 = "sha256-S0RqAyDPMTcv9vASMaE8eY1QexFysAOdnxUxFHIPOyE=";
    };
    date = "2026-04-02";
  };
  matugen-themes = {
    pname = "matugen-themes";
    version = "4695ea0d42167adceeaf2bc8fa9d5f6d62d4e271";
    src = fetchFromGitHub {
      owner = "InioX";
      repo = "matugen-themes";
      rev = "4695ea0d42167adceeaf2bc8fa9d5f6d62d4e271";
      fetchSubmodules = false;
      sha256 = "sha256-yWqUSVNIFxOqX2i4X8ccsZB5jPybv7hcFwY/rp2RSV0=";
    };
    date = "2026-04-02";
  };
  quickshell = {
    pname = "quickshell";
    version = "1eb3d8b4d0f192e98a75659eb33f286f3ce6bc34";
    src = fetchTarball {
      url = "https://git.outfoxxed.me/quickshell/quickshell/archive/1eb3d8b4d0f192e98a75659eb33f286f3ce6bc34.tar.gz";
      sha256 = "sha256-+7FeoO84DumLyIP8SOo6QWoP5y7AtypQ/t5zl8OWyhI=";
    };
    date = "2026-04-02";
  };
}
