# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bizhub-225i = {
    pname = "bizhub-225i";
    version = "2.0.1";
    src = fetchurl {
      url = "https://public.integration.yamayuri.kiku8101.com/publicdownload/download?fileId=B2C0B6D9-C563-4377-B77B-33BBAC4A5EC8";
      name = "bizhub-225i.zip";
      sha256 = "sha256-iF3FVSqDsjs6i4xeDMsUSb+0woCJ5/1lq7R0fe+x/HU=";
    };
  };
  dms-plugins = {
    pname = "dms-plugins";
    version = "141841fc85e01494df6d217bd5a27c65da87256d";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "141841fc85e01494df6d217bd5a27c65da87256d";
      fetchSubmodules = false;
      sha256 = "sha256-/155wFIotV9xiZzX9XRGs3ANjBcLJwS4kNDDNO6WkF0=";
    };
    date = "2026-02-24";
  };
  epson-202101w = {
    pname = "epson-202101w";
    version = "1.0.2";
    src = fetchurl {
      url = "https://download-center.epson.com/f/module/c863d6cc-2e0c-48f5-8a70-b2c3843c647a/epson-inkjet-printer-202101w-1.0.2-1.src.rpm";
      sha256 = "sha256-n0Ff2wfhPruYhzAH0GrhpYpkddiQ3rkYukvZyRgrn54=";
    };
  };
  matugen-themes = {
    pname = "matugen-themes";
    version = "e213a4ce7da91c69af91e1152390bf5cca346636";
    src = fetchFromGitHub {
      owner = "InioX";
      repo = "matugen-themes";
      rev = "e213a4ce7da91c69af91e1152390bf5cca346636";
      fetchSubmodules = false;
      sha256 = "sha256-MwS46euT8AjGyst3/P88LEq567wbb3ILAcDRX28CrRM=";
    };
    date = "2026-03-09";
  };
}
