# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bizhub-225i = {
    pname = "bizhub-225i";
    version = "2.0.1";
    src = fetchurl {
      url = "https://public.integration.yamayuri.kiku8101.com/publicdownload/download?fileId=B2C0B6D9-C563-4377-B77B-33BBAC4A5EC8";
      name = "bizhub-225i.zip";
      sha256 = "sha256-iF3FVSqDsjs6i4xeDMsUSb+0woCJ5/1lq7R0fe+x/HU=";
    };
  };
  epson-202101w = {
    pname = "epson-202101w";
    version = "1.0.2";
    src = fetchurl {
      url = "https://web.archive.org/web/20260318090110/https://download-center.epson.com/f/module/c863d6cc-2e0c-48f5-8a70-b2c3843c647a/epson-inkjet-printer-202101w-1.0.2-1.src.rpm";
      sha256 = "sha256-n0Ff2wfhPruYhzAH0GrhpYpkddiQ3rkYukvZyRgrn54=";
    };
  };
  home-manager-lib = {
    pname = "home-manager-lib";
    version = "f2d3e04e278422c7379e067e323734f3e8c585a7";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "home-manager";
      rev = "f2d3e04e278422c7379e067e323734f3e8c585a7";
      fetchSubmodules = false;
      sha256 = "sha256-kScKj3qJDIWuN9/6PMmgy5esrTUkYinrO5VvILik/zw=";
    };
    date = "2026-03-31";
  };
  matugen-themes = {
    pname = "matugen-themes";
    version = "5ff9df240985265c348b9d9a165b567121fb17c6";
    src = fetchFromGitHub {
      owner = "InioX";
      repo = "matugen-themes";
      rev = "5ff9df240985265c348b9d9a165b567121fb17c6";
      fetchSubmodules = false;
      sha256 = "sha256-cjaJojoB636M9aL9xfa3jAFfRyjXr5Zc6uZLTzXeIVw=";
    };
    date = "2026-03-29";
  };
  quickshell = {
    pname = "quickshell";
    version = "d6122277409783377059be6399004eb090a6008e";
    src = fetchTarball {
      url = "https://git.outfoxxed.me/quickshell/quickshell/archive/d6122277409783377059be6399004eb090a6008e.tar.gz";
      sha256 = "sha256-KWU38p8zEtgFOL5KZoWeqWVv27uBFLX3N+Ih+TFs9/0=";
    };
    date = "2026-03-31";
  };
}
