# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[[language]]
auto-format = true
name = "nix"

[[language]]
name = "nu"
auto-format = true
formatter = { command = "topiary-nushell", args = [
  "format",
  "--language",
  "nu",
] }

[language-server.nixd.config.nixd.options]
nixos.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").nixosConfigurations.tjmaxxer.options"
flake-parts.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").debug.options"
flake-parts-perSystem.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").currentSystem.options"

[language-server.tinymist]
command = "tinymist"
[language-server.tinymist.config]
formatterMode = "typstyle"
preview.background.enabled = true
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open",
]
