# SPDX-FileCopyrightText: 2026 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: ["push", "manual"]
    branch: ["main", "push-*"]
  # - event: ["pull_request"]
  #   branch: ["main"]

engine: "nixery"

# using the default values
clone:
  skip: false
  depth: 1
  submodules: false

dependencies:
  nixpkgs:
    - cachix
    - nix-fast-build
    - gnused
    - shadow
    - which
    - jq

steps:
  - name: "Bruteforce nix sandbox"
    command: |
      echo 'download-buffer-size = 500000000' >> /etc/nix/nix.conf
      echo 'substituters = https://cache.nixos.org/' >> /etc/nix/nix.conf
      echo 'trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=' >> /etc/nix/nix.conf

      sed -i '/false/d; /build-users-group/d' /etc/nix/nix.conf
      cat /etc/nix/nix.conf
      groupadd -r nixbld
      for n in $(seq 1 4); do useradd -c "Nix build user $n" \
      -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" \
      nixbld$n; done
      chown :nixbld /nix/{,store}

  - name: "Set extra substituters and prefetch inputs"
    environment:
      USER: "root"
    command: |
      cachix use nix-community
      cachix use machines
      nix flake prefetch-inputs .
      rm -rf /homeless-shelter
      nix flake archive --json \
      | jq -r '.path,(.inputs|to_entries[].value.path)' \
      | cachix push machines

  - name: "Check flake"
    environment:
      USER: "root"
    command: |
      cachix watch-exec machines -- \
      nix-fast-build --no-nom --skip-cached \
      --flake .#checks.x86_64-linux
