# SPDX-FileCopyrightText: 2026 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: ["push", "manual"]
    branch: ["main", "push-*"]
  # - event: ["pull_request"]
  #   branch: ["main"]

engine: microvm
image: nixos

registry:
  nixpkgs: github:nixos/nixpkgs/nixos-unstable

dependencies:
  - nix
  - cachix
  - nix-fast-build

caches:
  https://cache.nixos.org: "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
  https://nix-community.cachix.org: "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
  https://machines.cachix.org: "machines.cachix.org-1:imnXlKFUc4Iaedv6469v6TO37ruiNh6OfJN4le5bqdE="
  https://cache.forall.systems: "cache.forall.systems:5PmD7QO4MSF8YgyRZtkSGXRDo96H3bybIf2SsQh8ScI="

steps:
  - name: "Check flake"
    command: |
      nix flake check \
      --option extra-experimental-features "pipe-operators"
