[accessibility]
ui_scale = 1.1500000096857548

[bar.default]
background_opacity = 0.7499999832361937
center = ["clock", "control-center", "bar", "widget"]
end = [
  "media",
  "tray",
  "notifications",
  "clipboard",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "session",
]
position = "right"
scale = 1.400000013411045
smart_auto_hide = true
thickness = 40

[brightness]
enable_ddcutil = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = ["lockscreen-login-box@DP-2"]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 898.0
output = "DP-2"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[plugins]
enabled = ["icefish/phone-connect"]

[shell]
password_style = "random"
polkit_agent = true

[shell.panel]
transparency_mode = "soft"

[theme]
source = "wallpaper"

[theme.templates]
builtin_ids = [
  "alacritty",
  "btop",
  "gtk3",
  "gtk4",
  "ghostty",
  "helix",
  "kcolorscheme",
  "kitty",
  "niri",
  "qt",
]
community_ids = ["zen-browser", "steam", "zathura"]

[wallpaper]
directory = "/home/ssmvabaa/wallpapers"

[wallpaper.default]
path = "/home/ssmvabaa/wallpapers/wall.png"

[wallpaper.last]
path = "/home/ssmvabaa/wallpapers/wall.png"

[widget.bar]
type = "icefish/phone-connect:bar"

[widget.spacer_2]
type = "spacer"

[widget.tray]
drawer = true

[widget.widget]
type = "alexander/screen-toolkit:widget"
