# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Build installer ISO images"
on:
  push:
jobs:
  images:
    name: "Build a minimal image"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b #master
      - run: |
          nix build .#isoBootstrap
      - name: Release
        if: github.ref_type == 'tag'
        run: |
          gh release create "${GITHUB_REF_NAME}"
          gh release upload "${GITHUB_REF_NAME}" result/iso/*
