# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test machines"
on:
  # push:
  workflow_call:
jobs:
  tests:
    name: "Build machines"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31
      - uses: cachix/cachix-action@2b33705a8232e51ac94414b3b8c203d0a5e42ca3
        with:
          name: machines
          # If you chose signing key for write access
          # signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: cachix use nix-community
      - name: Build machines
        shell: nix shell github:Mic92/nix-fast-build --command bash --noprofile --norc -eo pipefail {0}
        run: |
          for machine in tjmaxxer disko-elysium msi-colgate; do
            nix-fast-build --no-nom --skip-cached --cachix-cache machines \
            --flake=.#nixosConfigurations."${machine}".config.system.build.toplevel
          done
