# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test machines"
on:
  # push:
  workflow_call:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  tests:
    name: "Build machines"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        machine: [tjmaxxer, disko-elysium, msi-colgate]
    steps:
      - name: Maximize Runner Space
        uses: justinthelaw/maximize-github-runner-space@master
        with:
          remove-android: "true"
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          # NOTE: Needs token for running actions
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.generate-token.outputs.token }}
      - uses: randymarsh77/static-nix-cache/setup@7e5e0f2e1ce2e252c5bd173122d069a139edbd51
      - name: Build ${{ matrix.machine }}
        run: |
          nix build  --max-jobs 64 --cores 0 --max-substitution-jobs 64 \
           --print-build-logs --keep-going --eval-profiler flamegraph \
          --accept-flake-config \
          .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
          nix shell nixpkgs#inferno -c \
          inferno-flamegraph nix.profile > ${{ matrix.machine }}-build.svg
      - uses: randymarsh77/static-nix-cache/deploy@7e5e0f2e1ce2e252c5bd173122d069a139edbd51
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          static: ./site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - uses: actions/deploy-pages@v4
        id: pages
      - uses: actions/upload-artifact@v6
        id: eval-artifact
        with:
          name: ${{ matrix.machine }} eval profile
          path: ${{ matrix.machine }}-build.svg
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message-id: ${{ matrix.machine }} eval profile
          message: "${{ matrix.machine }} eval profile: ${{ steps.eval-artifact.outputs.artifact-url }}"
