# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "All nixos-machines checks"
on:
  push:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
    inputs:
      ref:
        required: false
        type: string
jobs:
  check_flake:
    name: "Run flake checks"
    runs-on: ubuntu-latest
    environment: cachix
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # main
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            download-buffer-size = 500000000
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= machines.cachix.org-1:imnXlKFUc4Iaedv6469v6TO37ruiNh6OfJN4le5bqdE= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            substituters = https://machines.cachix.org https://nix-community.cachix.org https://cache.nixos.org/
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: machines
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Prefetch flake inputs
        run: |
          nix flake prefetch-inputs .
          nix flake archive --json \
          | jq -r '.path,(.inputs|to_entries[].value.path)' \
          | cachix push machines
      - name: Check flakes
        shell: "nix shell nixpkgs#nix-fast-build -c bash -e {0}"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix-fast-build --no-nom --skip-cached \
          --flake .#checks.x86_64-linux
