# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "All nixos-machines checks"
on:
  push:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
    inputs:
      ref:
        required: false
        type: string
jobs:
  check_flake:
    name: "Run flake checks"
    runs-on: ubuntu-latest
    environment: cachix
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}
      - uses: canidae-solutions/lix-quick-install-action@cdb5d0931be2223edbb9bad884341fcacdac298f # v4
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # master
        with:
          name: machines
          # If you chose signing key for write access
          # signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          # skipPush: true
      # - uses: DeterminateSystems/magic-nix-cache-action@b4a9864e3a8ab8179be30f2e70fd71fe9996bb9d # main
      - name: Check flakes
        shell: "nix shell nixpkgs#lixPackageSets.latest.nix-fast-build -c bash -e {0}"
        run: |
          nix-fast-build --no-nom --skip-cached \
          --option accept-flake-config true --cachix-cache machines \
          # --eval-max-memory-size 12288 --eval-workers 8 \
          # --flake ".#checks.$(nix eval --raw --impure --expr 'builtins.currentSystem')"
  check_ifd:
    name: "Run IFD checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}
      - uses: canidae-solutions/lix-quick-install-action@cdb5d0931be2223edbb9bad884341fcacdac298f # v4
      - name: Check IFD
        run: "nix flake check --no-build --no-allow-import-from-derivation"
